version: '3'
services:
  mongodb:
    image: mongo
    ports: 
     - 27017:27017
    environment:
     - MONGO_INITDB_ROOT_USERNAME=admin
     - MONGO_INITDB_ROOT_PASSWORD=secret
  
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
    - ME_CONFIG_MONGODB_ADMINUSERNAME=admin 
    - ME_CONFIG_MONGODB_ADMINPASSWORD=secret
    - ME_CONFIG_MONGODB_SERVER=mongodb

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"