version: '3'
networks: 
  mongo-network:

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    networks:
      - mongo-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin 
      - ME_CONFIG_MONGODB_ADMINPASSWORD=secret
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      - mongo-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    container_name: frontend
    networks:
      - mongo-network

  backend:
    build:
      context: ./backend  # Change the context to the root directory
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: backend
    environment:
      - MONGODB_URL: mongodb://mongodb:27017
    networks:
      - mongo-network
    
